version: '3'
services:
  postgres:
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    container_name: backend_postgres
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_PASSWORD=localdb
    volumes:
      - data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "8080"
      - "5432"
    ports:
      - "5432:5432"
      - "8080:8080"

  nakama:
    build: .
    container_name: backend
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
          /nakama/nakama migrate up --database.address postgres://postgres:localdb@postgres:5432/nakama &&
          exec /nakama/nakama --config /nakama/data/local.yml --database.address postgres://postgres:localdb@postgres:5432/nakama
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./files:/nakama/data/files      
    expose:
      - "7349"
      - "7350"
      - "7351"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    healthcheck:
      test: ["CMD", "/nakama/nakama", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  data: